name: CI/CD

on:
  push:
    branches: [ "main" ]
  
env:
  REPOSITORY_NAME: ${{ github.event.repository.full_name }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get dynamic tag by date
        run: | 
         eval "$(date +'h=%H m=%M s=%S')"
         seconds_since_midnight="$((${h#0} * 3600 + ${m#0} * 60 + ${s#0}))"
         echo "TAG=$(date +%y.%m.%d.$seconds_since_midnight)" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Register
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}
            ghcr.io/${{ env.REPOSITORY_NAME }}:latest
